-- -----------------------------------------------------
-- Insertion dans la table produit
-- -----------------------------------------------------
INSERT INTO Produit VALUES
(1,'Poulet', 'poulet.png', 'Le bon poulet de chez Loue', 5, 10, 1),
(2,'Thon', 'saupiquet.png', 'Le bon thon de chez Saupiquet', 5, 10, 1),
(3,'Merguez', 'merguez.png', 'Elle est bonne ma merguez', 5, 10, 1),
(4,'Steak', 'charal.png', 'Le bon steak de chez Charal', 5, 10, 1),
(5,'Saumon', 'petitNavire.png', 'Le bon poisson de chez petit navire (sauf le lundi)', 5, 10, 1),
(6,'Carotte', 'carotte.png', 'Carotte France', 5, 10, 2),
(7,'Banane', 'banane.png', 'Banane Martinique', 5, 10, 2),
(8,'Pomme', 'pomme.png', 'Pomme Portugal', 5, 10, 2),
(9,'Poireau', 'poireau.png', 'Poireau Allemagne', 5, 10, 2),
(10,'Fraise', 'fraise.png', 'Fraise Espagnol', 5, 10, 2),
(11,'Granola', 'granola.png', 'Meilleur que les pepitos', 5, 10, 3),
(12,'Café', 'cafe.png', 'Pour rester éveillé', 5, 10, 3),
(13,'PastaBox', 'pastabox.png', 'Des pates en conserves', 5, 10, 3),
(14,'Moutarde', 'moutarde.png', 'Exclusivement de Dijon', 5, 10, 3),
(15,'Biscotte', 'heudebert.png', 'Heudebert un vrai savoir faire', 5, 10, 3),
(16,'Jus de tomate', 'jusdetomate.png', 'Les meilleurs gaspachos se font avec du jus de tomate', 5, 10, 4),
(17,'Grenadine', 'grenadine.png', 'Encore meilleur avec des glaçons', 5, 10, 4),
(18,'Coca Cola', 'coca-cola.png', 'Même le père noël en boit', 5, 10, 4),
(19,'Perrier', 'perrier.png', 'Perrier, c est fou', 5, 10, 4),
(20,'Jus d\'orange', 'jusdorange.png', 'Fini les réveils difficiles', 5, 10, 4),
(21,'Poêlée de légumes', 'poele.png', 'Plein de légumes, pas de jaloux', 5, 10, 5),
(22,'Pizza', 'pizza.png', 'Chaude ou froide on adore la manger', 5, 10, 5),
(23,'Petit pois', 'petitpois.png', 'Petit mais costaud', 5, 10, 5),
(24,'Frites', 'frites.png', 'McCain meilleur que bon', 5, 10, 5),
(25,'Amuse bouche', 'amusebouchedelamer.png', 'Pour vos apéritifs', 5, 10, 5),
(26,'Dentifrice', 'dentifrice.png', 'Une haleine toujours fraiche', 5, 10, 6),
(27,'Shampoing', 'shampoing.png', 'Des cheuveux toujours soyeux', 5, 10, 6),
(28,'Savon', 'savon.png', 'Pour sentir bon', 5, 10, 6),
(29,'Mousse a raser', 'moussearaser.png', 'Pour les hommes et femmes a barbes', 5, 10, 6),
(30,'Gel douche', 'geldouche.png', 'Pour sentir bon', 5, 10, 6);